tasks:
  - before: |
      wget -qOCodeGraph.zip https://codejudge-artifacts.s3.amazonaws.com/CodeGraph.zip
      unzip CodeGraph.zip
  - init: echo clean
    command: echo hi
ports:
  - port: 8080
    onOpen: open-preview
    visibility: public
vscode:
  extensions:
    - vscjava.vscode-java-pack
    - gabrielbb.vscode-lombok
